server:
  port: 9100

spring:
  application:
    name: msvc-attributes

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/traccar
    username: postgres
    password: root
    jpa:
      hibernate:
        ddl-auto: create-drop
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka